### PR TITLE
Further Checkbox component refinement

### LINKED ISSUE #59: Stop using ::after hack for checkboxes/radios
The markup for checkboxes should just be `<input type="checkbox" class="checkbox">`, nothing else... It doesn't make sense IMO to force putting a label as a wrapper and as a sibling element.

Plus, Firefox and Chrome (and possibly other major browsers, but I haven't checked), support styling `<input type="checkbox">` directly using -moz-appearance: none;

### PR DESCRIPTION
**Pull request by lmorchard**
Fixes #59

### CODE REVIEW

**Comment by lmorchard** [comment]
Didn't know about `-{moz,webkit}-appearance` before now. These changes seem to work for Firefox, Chrome, and Edge on Windows and simplify the markup a bunch.

**Comment by lmorchard** [comment]
# GitHub Pages Deployment
Pull Request:
https://FirefoxUX.github.io/photon-components-web/pull/60
Branch:
https://FirefoxUX.github.io/photon-components-web/branches/59-better-checkbox
Storybook:
https://FirefoxUX.github.io/photon-components-web/commits/21e060c9b655dd545230ba5f62f4128aeca6c352/
Build:
https://FirefoxUX.github.io/photon-components-web/commits/21e060c9b655dd545230ba5f62f4128aeca6c352/dist.zip

**Comment by lmorchard** [comment]
# GitHub Pages Deployment
Pull Request:
https://FirefoxUX.github.io/photon-components-web/pull/60
Branch:
https://FirefoxUX.github.io/photon-components-web/branches/59-better-checkbox
Storybook:
https://FirefoxUX.github.io/photon-components-web/commits/922df6c37bc36efc1197f1073a1630c013f780ca/
Build:
https://FirefoxUX.github.io/photon-components-web/commits/922df6c37bc36efc1197f1073a1630c013f780ca/dist.zip

**Comment by lmorchard** [comment]
# GitHub Pages Deployment
Pull Request:
https://FirefoxUX.github.io/photon-components-web/pull/60
Branch:
https://FirefoxUX.github.io/photon-components-web/branches/59-better-checkbox
Storybook:
https://FirefoxUX.github.io/photon-components-web/commits/819a890b1e30bacbcac6414f362d4b3eca81de28/
Build:
https://FirefoxUX.github.io/photon-components-web/commits/819a890b1e30bacbcac6414f362d4b3eca81de28/dist.zip

**Comment by lmorchard** [comment]
# GitHub Pages Deployment
Storybook:
https://FirefoxUX.github.io/photon-components-web/commits/6127a39fbcf09223bb6983112b84bb8d1e4c94fd/
Build:
https://FirefoxUX.github.io/photon-components-web/commits/6127a39fbcf09223bb6983112b84bb8d1e4c94fd/dist.zip

**Comment by lmorchard** [comment]
# GitHub Pages Deployment
Storybook:
https://FirefoxUX.github.io/photon-components-web/commits/3d0625cc0956faaf791538fbe6f87177e4e1c485/
Build:
https://FirefoxUX.github.io/photon-components-web/commits/3d0625cc0956faaf791538fbe6f87177e4e1c485/dist.zip

**Comment by meandavejustice** [comment]
fixed up a merge conflict with the github interface ^^

**Comment by lmorchard** [comment]
Did another rebase on master and squashed the commits

**Comment by lmorchard** [comment]
# GitHub Pages Deployment
Storybook:
https://FirefoxUX.github.io/photon-components-web/commits/bc6ddcd15650820407398110b4dce6108e0bc2b6/
Build:
https://FirefoxUX.github.io/photon-components-web/commits/bc6ddcd15650820407398110b4dce6108e0bc2b6/dist.zip

**Comment by lmorchard** [comment]
# GitHub Pages Deployment
Storybook:
https://FirefoxUX.github.io/photon-components-web/commits/0df99cb76e1c1d64da54d5dd0db951ccfe0966b5/
Build:
https://FirefoxUX.github.io/photon-components-web/commits/0df99cb76e1c1d64da54d5dd0db951ccfe0966b5/dist.zip

**Comment by lmorchard** [comment]
Pushed tweaks to switch check icons and will file a follow-up issue. Also added [some story-specific CSS](https://github.com/FirefoxUX/photon-components-web/pull/60/files#diff-6cdf2ca822c9c6bc9c0341e5b73a550dR7) that expands the checkbox labels to the full width of the containing list items. 

I didn't stick that in the CSS for the checkbox component overall, though: I'm not sure if we want to prescribe the width and inline-block display. But, we can move it into there if it's universally useful.

**Pull request merged**
