### PR TITLE
Initial Tree implementation

### PR DESCRIPTION
**Pull request by lmorchard**
Issue #28

### CODE REVIEW

**Comment by lmorchard** [comment]
# GitHub Pages Deployment
Storybook:
https://FirefoxUX.github.io/photon-components-web/commits/eff986f69bb82a03ee8e7c55e2f0205cdc6027a2/
Build:
https://FirefoxUX.github.io/photon-components-web/commits/eff986f69bb82a03ee8e7c55e2f0205cdc6027a2/dist.zip

**Comment by lmorchard** [comment]
Yeah, this is a very handwavy PR. The spec kind of confused be as to exactly what we want for this component. There are at least 3 variants and a couple of themes represented there. Do we want all of those in one component with a switch? Separate components?

**Comment by bwinton** [comment]
Yeah. _And_ there's the other trees that ntim mentioned in the issue… 🙂

**Comment by meandavejustice** [comment]
This looks like a reasonable starting point, I say we merge and continue iterating

**Pull request merged**
